version: '3'
services:
  mobile-web-best-practice: #项目的 service name
    container_name: 'mobile-web-best-practice-container' #容器名称
    image: nginx #指定镜像
    restart: always
    ports:
      - 8001:80
    volumes:
      #~ 将宿主机上的本项目的 nginx.conf 文件映射到容器内的 /etc/nginx 文件
      - ./nginx.conf:/etc/nginx/nginx.conf #挂载 nginx 配置
      #~ 将宿主机上的本项目映射到容器的 /usr/share/nginx/html
      - ./:/usr/share/nginx/html/ #挂载项目
    privileged: true
